remote_theme: pages-themes/slate@v0.2.0
title: Ernest's Neural Data Science Portfolio
description: Here's a short snippet at the work I've been doing as a part of NESC3505 Neural Data Science class. 
